### ISSUE TITLE
Malfunction after  dist-upgrade  in Ubuntu 16.04

### ISSUE THREAD

**Issue by npapadimitriou** [eliostvs/tomate-gtk#34]
Hi 
After doing a `sudo apt-get dist-upgrade` ,  the application started malfunctioning. 
 button replay  disappeared, 
button minimize disappeared,
indication over pomodoro number disappeared
close button changed position,
settings button changed icon and in tab "Extensions" you can no longer see the list of extensions.

Following screenshots
![screenshot from 2019-02-20 14-26-48](https://user-images.githubusercontent.com/13378588/53095409-1427ff00-351d-11e9-870e-b0a5e3f040ca.png)
![screenshot from 2019-02-20 14-27-19](https://user-images.githubusercontent.com/13378588/53095415-1722ef80-351d-11e9-9352-e351c589101b.png)

Please your help cause I love this application

**Comment by eliostvs** [comment]
Hi,

I'm sorry if the last update broken your previous experience. 

Now Tomate is using a Gtk.HeaderBar instead of a Gtk.Toolbar to use better the window space. In this type of widget the close/minimize buttons are to the right of the window and I chose to not show the minimize button to save space, as you known if you try to close the window when the timer is running the window will minimize if you don't have any tray plugin enabled. 

I don't know what you mean by *replay* button, but the reset button is on the right side of the play button and as always will be clickable when you have at lest 1 pomodoro finished, by the way the count of session is in the "header" now, on the right side of the reset button. In your picture you not finished any pomodoro, so the message is "no session yet", when you finish a pomodoro, the text will change to "Session 1", where 1 is the session you are in. 

About the plugins, could you tell me which one are you using and in which version?

**Comment by npapadimitriou** [comment]
Yes the reset button instead of replay. I wanted to say that the icon disappeared and instead there is an icon that looks like  Html alt thing.
As it comes to plugins 
1.StatusIcon(0.6)
2.Launcher(0.8)
3.Notify(0.1)
4.Alarm(0.8)

In addition I would like to add that the fade in/out windows informing about session finishing or that it has to start has become more like "Warning" windows in which exit/minimize works and if you click everywhere else apart from the Headerbar and inside the window it closes. 
I attach screenshots

![screenshot from 2019-02-27 19-07-27](https://user-images.githubusercontent.com/13378588/53523538-61880b80-3add-11e9-8833-bf2d9dfb26b5.png)
![screenshot from 2019-02-27 19-07-42](https://user-images.githubusercontent.com/13378588/53523541-6482fc00-3add-11e9-95d3-be00fcf8c681.png)

**Comment by eliostvs** [comment]
About the notification plugin. This windows is showing up on your system because the notification has been configured with an infinity timeout. I made a release of tomate-notify-plugin version 0.11.0 that removes this setting.

**Comment by npapadimitriou** [comment]
Yes I upgraded it! Thanks a lot for your time and for this app
