### ISSUE TITLE
cannot install on Linux Mint 18.3 - repository does not have a Release file

### ISSUE THREAD

**Issue by waynongithub** [eliostvs/tomate-gtk#35]
Hi, I'm trying to install Tomate using the instructions for Ubuntu 16.04. I get the message: 
The repository 'http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_18.3 ./ Release' does not have a Release file. 
[...]
Failed to fetch http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_18.3/./Packages  404  Not Found
How can I proceed?
Thanks

**Comment by eliostvs** [comment]
Hi,
If your distro is based on **Ubuntu 16.04** the repository should be **http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_16.04 ./**. It will be easier if you follow the installation instructions again, but in the first step set the value of variable **RELEASE** to **16.04** instead of running the sed script. I will update the docs to prevent other Mint users from having the same problem. Thanks for your report!

**Comment by waynongithub** [comment]
that worked, thank you
