### ISSUE TITLE
Repository Signature Key Expired

### ISSUE THREAD

**Issue by paradx** [eliostvs/tomate-gtk#53]
The Key used for signing the apt packages: 
expired on the 4th of December and would require an update: 

from apt-key list:
```
pub   rsa2048 2015-02-13 [SC] [expired: 2023-12-04]
      DCF5 D046 3AE9 9F52 9DDD  F0B2 3126 A343 8CA9 B269
uid           [ expired] home:eliostvs OBS Project <home:eliostvs@build.opensuse.org>
 ```
 
 apt update will produce the expected error as well.

**Comment by eliostvs** [comment]
Hi, probably you need to download the new key:

```bash
RELEASE=`sed -n 's/VERSION_ID="\(.*\)"/\1/p' /etc/os-release`
curl -fsSL "http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_$RELEASE/Release.key" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/tomate.gpg > /dev/null
```

And delete the old one. I think the old key path is `/etc/apt/trusted.gpg.d/tomate.asc`.  I'm not sure.

**Comment by paradx** [comment]
Hi, 

thanks for the quick respond (and great tool). 
I removed  ```/etc/apt/trusted.gpg.d/tomate.gpg``` and did the setup as well your proposed solution, same error. 

What is the key ID of the new key?  

$RELEASE is 22.04
tomate.list:

``` 
deb http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_22.04/ ./
```


I used ``` sudo apt-key del DCF5D0463AE99F529DDDF0B23126A3438CA9B269 ``` to delete the old key and changed the tomate.list to 

```
deb [signed-by=/etc/apt/trusted.gpg.d/tomate.gpg] http://download.opensuse.org/repositories/home:/eliostvs:/tomate/xUbuntu_22.04/ ./
```

now apt doesn't complain anymore, maybe adding this to the install script would also work out of the box with the old key still in the system.

**Comment by eliostvs** [comment]
I'm glad it's working. I tried to replicate this issue in a Docker image. The original key path was "/etc/apt/trusted", so you would need to use "sudo apt-key del DCF5D0463AE99F529DDDF0B23126A3438CA9B269" as you suggested. Interestingly, the expiration date is higher in a clean installation. Regardless, you need to use the new method to install the key, otherwise you will start receiving the warning: "Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))."

![Screenshot from 2023-12-07 20-33-17](https://github.com/eliostvs/tomate-gtk/assets/1129420/d9206777-4480-4228-a55f-b7228f5c0c9b).
